# Form implementation generated from reading ui file 'frontend/ui/list_item.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form, item):
        Form.setObjectName("Form")
        Form.resize(323, 161)
        self.name = QtWidgets.QLabel(parent=Form)
        self.name.setGeometry(QtCore.QRect(20, 10, 151, 61))
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 151, 61))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form, item)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form, item):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name.setText(f'{item['name']}')
        self.label_2.setText(f"{item['count']}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
